Action:
  Default:
    aux:
      waist: 0
      neck: 0
    gripper:
      left: 0
      right: 0
    locomotion: 0
    trajectory:
      left_pos:
      - 0.2
      - 0.1
      - 0.4
      left_quat:
      - 0.06
      - -0.31
      - -0.06
      - 0.95
      right_pos:
      - 0.2
      - -0.1
      - 0.4
      right_quat:
      - -0.06
      - -0.31
      - -0.06
      - 0.95
  Map:
    aux:
      waist:
        0: default
      neck:
        0: forward
        1: down
        2: up
    gripper:
      left:
        0: release
        1: grasp
      right:
        0: release
        1: grasp
    locomotion:
      0: balance
      1: walk_forward
      2: walk_backward
      3: sidewalk_left
      4: sidewalk_right
      5: turning_left
      6: turning_right
      7: balance
Aux Control:
  Action:
    neck:
      forward: 
        head_pitch: 0.0
        head_roll: 0.0
        head_yaw: 0.0
      down: 
        head_pitch: 0.3
        head_roll: 0.0
        head_yaw: 0.0
      up: 
        head_pitch: -0.3
        head_roll: 0.0
        head_yaw: 0.0
    waist:
      default: 
        waist_pitch: 0.0
        waist_roll: 0.0
        waist_yaw: 0.0
  Gain:
    kd:
      head_pitch: 2.0
      head_roll: 2.0
      head_yaw: 2.0
      waist_pitch: 20.0
      waist_roll: 20.0
      waist_yaw: 20.0
    kp:
      head_pitch: 10.0
      head_roll: 10.0
      head_yaw: 10.0
      waist_pitch: 100.0
      waist_roll: 100.0
      waist_yaw: 100.0
Gripper Control:
  Action:
    left:
      grasp: 0.33
      release: -0.33
    right:
      grasp: 0.33
      release: -0.33
  Gain:
    left:
      kd: 1000.0
      kp: 50000.0
    right:
      kd: 1000.0
      kp: 50000.0
Joint-Space Control:
  kd:
    l_ankle_fe: 0.0
    l_ankle_ie: 0.0
    l_elbow_fe: 0.0
    l_hip_aa: 0.0
    l_hip_fe: 0.0
    l_hip_ie: 0.0
    l_knee_fe_jd: 0.0
    l_knee_fe_jp: 0.0
    l_shoulder_aa: 0.0
    l_shoulder_fe: 0.0
    l_shoulder_ie: 0.0
    l_wrist_pitch: 0.0
    l_wrist_ps: 0.0
    neck_pitch: 0.0
    r_ankle_fe: 0.0
    r_ankle_ie: 0.0
    r_elbow_fe: 0.0
    r_hip_aa: 0.0
    r_hip_fe: 0.0
    r_hip_ie: 0.0
    r_knee_fe_jd: 0.0
    r_knee_fe_jp: 0.0
    r_shoulder_aa: 0.0
    r_shoulder_fe: 0.0
    r_shoulder_ie: 0.0
    r_wrist_pitch: 0.0
    r_wrist_ps: 0.0
  kp:
    l_ankle_fe: 1.0
    l_ankle_ie: 1.0
    l_elbow_fe: 1.0
    l_hip_aa: 1.0
    l_hip_fe: 1.0
    l_hip_ie: 1.0
    l_knee_fe_jd: 1.0
    l_knee_fe_jp: 1.0
    l_shoulder_aa: 1.0
    l_shoulder_fe: 1.0
    l_shoulder_ie: 1.0
    l_wrist_pitch: 1.0
    l_wrist_ps: 1.0
    neck_pitch: 1.0
    r_ankle_fe: 1.0
    r_ankle_ie: 1.0
    r_elbow_fe: 1.0
    r_hip_aa: 1.0
    r_hip_fe: 1.0
    r_hip_ie: 1.0
    r_knee_fe_jd: 1.0
    r_knee_fe_jp: 1.0
    r_shoulder_aa: 1.0
    r_shoulder_fe: 1.0
    r_shoulder_ie: 1.0
    r_wrist_pitch: 1.0
    r_wrist_ps: 1.0
Manipulation:
  Duration:
    Reaching: 0.01
    Reaching Trans: 0.1
    Returning Trans: 0.1
  Hand Velocity Max: 10.0
  Initial Target:
    LH Pos:
      - -0.24
      - -0.34
      - 0.92
    LH Quat:
      - .61
      - -0.35
      - .61
      - -0.35
    RH Pos:
      - -0.24
      - 0.34
      - 0.92
    RH Quat:
      - -0.61
      - -0.35
      - -0.61
      - -0.35
  Trajectory Mode: interpolation
  Workspace:
    LH Max:
    - 1
    - 1
    - 1
    LH Min:
    - -1
    - -1
    - -1
    RH Max:
    - 1
    - 1
    - 1
    RH Min:
    - -1
    - -1
    - -1
Simulation:
  Control Period: 0.005
  Initial State:
    Aux Pos:
      head_pitch: 0.0
      head_roll: 0.0
      head_yaw: 0.0
      waist_pitch: 0.0
      waist_roll: 0.0
      waist_yaw: 0.0
    Body Pos:
    - 0.0
    - 0.0
    - 0.76
    Body Quat:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    Joint Pos:
      l_ankle_pitch: -0.7854
      l_ankle_roll: -0.087266
      l_elbow_pitch: -1.5708
      l_hip_pitch: -0.7854
      l_hip_roll: 0.087266
      l_hip_yaw: 0.0
      l_knee_pitch: 1.5708
      l_shoulder_pitch: 0.0
      l_shoulder_roll: 0.5236
      l_shoulder_yaw: 0.0
      l_wrist_pitch: 0.0
      l_wrist_roll: 0.0
      l_wrist_yaw: 0.0
      r_ankle_pitch: -0.7854
      r_ankle_roll: 0.087266
      r_elbow_pitch: -1.5708
      r_hip_pitch: -0.7854
      r_hip_roll: -0.087266
      r_hip_yaw: 0.0
      r_knee_pitch: 1.5708
      r_shoulder_pitch: 0.0
      r_shoulder_roll: -0.5236
      r_shoulder_yaw: 0.0
      r_wrist_pitch: 0.0
      r_wrist_roll: 0.0
      r_wrist_yaw: 0.0
      head_yaw: 0.0
      head_pitch: 0.0
      head_roll: 0.0
      waist_yaw: 0.0
      waist_pitch: 0.0
      waist_roll: 0.0
  Save Data: true
  Save Frequency: 1
  Verbose: false
Walking:
  Alpha DS: 0.7
  Duration:
    Additional Inititial Transfer: .5
    Contact Trans: 1.0
    Initial Stand: 1.5
    RF Z Max: 0.05
    Swing: 1
  Initial Motion:
    Backward Step: -0.2
    COM Height: 0.7
    Footwidth: 0.32
    Forward Step: 0.2
    Strafe Distance: 0.2
    Swing Height: 0.07
    Trun Angle: .31416
  Percentage Settle: 0.999
Whole-Body Contol:
  Hierarchy:
    CAM: 2.0
    COM: 20.0
    Contact Foot: 60.0
    Hand Pos Max: 10
    Hand Pos Min: 2
    Hand Quat Max: 10
    Hand Quat Min: 2
    Swing Foot: 40.0
    Torso: 40.0
    Upper Body: 1.0
  Integration:
    Cutoff Frequency:
      Joint Pos: 1.0
      Joint Vel: 2.0
    Joint Pos Error Max: 0.2
  RF Z Max: 1000.0
  Reguralization:
    Q ddot: 1.0e-08
    RF: 1.0e-07
  Use Torque Limit: false
  kp:
    COM:
    - 400
    - 400
    - 400
    CAM:
    - 0.0
    - 0.0
    - 0.0
    Torso:
    - 100
    - 100
    - 100
    Hand Pos:
    - 300.0
    - 300.0
    - 300.0
    Hand Quat:
    - 200.0
    - 200.0
    - 200.0
    Foot Pos:
    - 500.0
    - 500.0
    - 500.0
    Foot Quat:
    - 500.0
    - 500.0
    - 500.0
    Upper Body:
    - 40
    - 40
    - 40
    - 40
    - 40
    - 40
    - 40
    - 40
    - 40
    - 40
    - 40
    - 40
    - 40
    - 40
    - 20
    - 20
    - 20
    - 600
    - 600
    - 600
  kd:
    COM:
    - 5.0
    - 5.0
    - 5.0
    CAM:
    - 10.0
    - 10.0
    - 10.0
    Torso:
    - 20
    - 20
    - 20
    Hand Pos:
    - 50
    - 50
    - 50
    Hand Quat:
    - 30
    - 30
    - 30
    Foot Pos:
    - 60.0
    - 60.0
    - 60.0
    Foot Quat:
    - 60.0
    - 60.0
    - 60.0
    Upper Body:
    - 20
    - 20
    - 20
    - 20
    - 20
    - 20
    - 20
    - 20
    - 20
    - 20
    - 20
    - 20
    - 20
    - 20
    - 20
    - 20
    - 20
    - 100
    - 100
    - 100
